### ISSUE TITLE
I don't want use docker

### ISSUE THREAD

**Issue by pangqiss1986** [carbolymer/mtr-monitor#4]
dear:
      THE mtr monitor is very good!.BUT I don't want to use docker. Now I install influxdb.How can I create database ,tables,column?
      and THE save_data.py hava  you  python2 ?
      Thank you!

**Comment by carbolymer** [comment]
check available options here: 
https://github.com/carbolymer/mtr-monitor/blob/master/mtr-monitor.sh#L10

You don't need to create schema in influxdb. Everything is done in https://github.com/carbolymer/mtr-monitor/blob/master/save_data.py

You just need to set correct port and host in `mtr-monitor.sh`

**Comment by pangqiss1986** [comment]
this is my  mtr-monitor.sh
#!/bin/bash
# number of pings sent
CYCLES=30
# inverval between MTR tests in seconds
INTERVAL=30
MTR_HOSTS=("114.114.114.114")
# if you need to change it, change also in influx-cli.sh
INFLUXDB_HOST="localhost"
INFLUXDB_PORT=8086
# END OF CONFIG
function monitor_mtr() {
  for MTR_HOST in "${MTR_HOSTS[@]}"; do
    ( mtr --report --json --report-cycles $CYCLES $MTR_HOST | ./save_data.py --host $INFLUXDB_HOST --port $INFLUXDB_PORT ) &
  done
}

which mtr &>/dev/null
if [ $? -eq 1 ]; then
  echo "mtr is not available on this system - it is required for this script to work"
  exit 1
fi

while true; do
  monitor_mtr
  sleep $INTERVAL
done

THE save_data.py  must use python3?

**Comment by carbolymer** [comment]
looks fine, and yes you should use python 3

**Comment by pangqiss1986** [comment]
THANK YOU!

**Comment by pangqiss1986** [comment]
sorry,I have two question....
NO.1:
(py3) [root@localhost mtr]# ./mtr-monitor.sh 
mtr: unrecognized option '--json'
mtr: unrecognized option '--json'
mtr: unrecognized option '--json'
mtr: unrecognized option '--json'
Traceback (most recent call last):
  File "./save_data.py", line 65, in <module>
    main()
  File "./save_data.py", line 38, in main
    mtr_result = json.load(sys.stdin)
  File "/usr/local/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

NO.2
grafana version is 6.1.4   THE grafana_dashboard_mtr.json    import is
Templating init failed
Datasource named ${DS_TBD_INFLUX MTR} was not found

can you help me...thank!!!

**Comment by carbolymer** [comment]
1. which mtr version you have? you need >=0.87

2. You need to setup datasource manually in grafana

**Comment by pangqiss1986** [comment]
1.I use centos7.   mtr version is 0.85.    I can't fand  >=0.87   in centos7.。。   0.85  is not support json??
2.yes.I finish datasource in grafana...

**Comment by pangqiss1986** [comment]
the grafana_dashboard_mtr.json import is not support  grafana6.1.4.....

**Comment by teesa-git** [comment]
@pangqiss1986 @carbolymer  The same quessiton No.1
